// <auto-generated />
using HappyHeadlines.Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HappyHeadlines.Db.Migrations.Profanity
{
    [DbContext(typeof(ProfanityDbContext))]
    [Migration("20260910082032_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HappyHeadlines.Db.Entities.ProfanityWord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Word")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Word")
                        .IsUnique();

                    b.ToTable("ProfanityWords", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Word = "damn"
                        },
                        new
                        {
                            Id = 2,
                            Word = "hell"
                        },
                        new
                        {
                            Id = 3,
                            Word = "crap"
                        },
                        new
                        {
                            Id = 4,
                            Word = "bloody"
                        },
                        new
                        {
                            Id = 5,
                            Word = "arse"
                        },
                        new
                        {
                            Id = 6,
                            Word = "bugger"
                        },
                        new
                        {
                            Id = 7,
                            Word = "shit"
                        },
                        new
                        {
                            Id = 8,
                            Word = "piss"
                        },
                        new
                        {
                            Id = 9,
                            Word = "dick"
                        },
                        new
                        {
                            Id = 10,
                            Word = "bastard"
                        },
                        new
                        {
                            Id = 11,
                            Word = "asshole"
                        },
                        new
                        {
                            Id = 12,
                            Word = "bollocks"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
